version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gorm.io/gorm
    versions:
    - 1.21.1
    - 1.21.2
    - 1.21.3
    - 1.21.4
    - 1.21.5
    - 1.21.6
    - 1.21.7
    - 1.21.8
  - dependency-name: github.com/gin-gonic/gin
    versions:
    - 1.7.0
  - dependency-name: gorm.io/driver/mysql
    versions:
    - 1.0.5
